version: '3.8'

services:
  wishlistdb:
    image: postgres:latest
    container_name: wishlistdb
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - wishlistdbdata:/var/lib/postgresql/data
    networks:
      - wishlistdockernet

  web:
    build: .
    image: wishlistweb
    container_name: wishlistweb
    restart: always
    depends_on:
      - wishlistdb
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - wishlistwebdata:/app/web
    networks:
      - wishlistdockernet

volumes:
  wishlistdbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${WORK_DIR}/wishlistdbdata/'
  wishlistwebdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${WORK_DIR}/wishlistwebdata/'


networks:
  wishlistdockernet:
    name: wishlistdockernet
    external: true

